# Generated by Django 5.0.1 on 2024-01-11 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='core.post'),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post_id', 'user_id')},
        ),
    ]
